name: .NET Core

on: [push, pull_request]
jobs:
  build:

    name: Github Actions Build
    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}
    - name: Build with dotnet
      run: dotnet build src/ --configuration Release --nologo
    - name: Run tests
      run: dotnet test src/graphiql.tests/ --configuration Development --nologo
    # - if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || contains(github.ref, 'tags'))
    #   name: Push CI
    #   run: ./push.sh ${{ secrets.FEEDZ_KEY }}
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1